[env:deskmon]
platform = espressif32@6.11.0
board = esp32-s3-devkitm-1
framework = arduino
monitor_speed = 115200

build_flags = 
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D CONFIG_ASYNC_TCP_RUNNING_CORE=0

lib_deps =
    adafruit/Adafruit GFX Library @ ^1.11.9
    adafruit/Adafruit ST7735 and ST7789 Library @ ^1.10.3
    adafruit/Adafruit BusIO @ ^1.16.1
    adafruit/Adafruit SSD1306 @ ^2.5.9
    rfetick/MPU6050_light @ ^1.1.0
    QMC5883LCompass
    links2004/WebSockets @ ^2.4.1
    bblanchon/ArduinoJson @ ^7.1.0
    